name: TGæ¨é€

on:
  push:
    branches:
      - main
    paths:
      - 'addressesapi.txt'
  workflow_dispatch:  # æ‰‹åŠ¨è§¦å‘

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: åŠ è½½å½“å‰çš„ GitHub åº“
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get Beijing Time
      id: time
      run: |
        TIME_ZONE="Asia/Shanghai"
        CURRENT_TIME=$(TZ=${TIME_ZONE} date +"%Y-%m-%d %H:%M:%S")
        echo "::set-output name=current_time::${CURRENT_TIME}"
      
    - name: æ‰§è¡Œæ¨é€
      run: |
        head -n 8 addressesapi.txt > addressesapi_truncated.txt
        while IFS= read -r line; do
          ips+=$'\n'"$(echo "$line" | sed 's/#/, /g')"
        done < addressesapi_truncated.txt
        message="ä»Šæ—¥ä¼˜é€‰ For: ${{ steps.time.outputs.current_time }}
        $ips
        ...æ›´å¤šä¼˜é€‰IPå¯é€šè¿‡è‡ªå®šä¹‰è®¢é˜…æ–¹å¼è·å–
        https://sub.cmliucdn.tk/sub?host=<ä½ çš„VlessåŸŸå>&uuid=<ä½ çš„UUID>&path=<ä½ çš„wsè·¯å¾„>
        
        å¦‚æœä½ çš„vlessæ˜¯é€šè¿‡workeréƒ¨ç½²ä¸”æ²¡æœ‰pathå‚æ•°,å¯å¡«å…¥ä»¥ä¸‹å¯¹åº”å‚æ•°åè®¢é˜…èŠ‚ç‚¹ä¿¡æ¯
        https://sub.cmliucdn.tk/sub?host=<ä½ çš„WorkeråŸŸå>&uuid=<ä½ çš„UUID>
        å®é™…ä½¿ç”¨æ—¶è¯·å»æ‰<>ç¬¦å·
        æ³¨æ„ï¼šæ‚¨å¯ä»¥å°†æ­¤é“¾æ¥åˆ†äº«ä¼ æ’­åˆ°ä»»ä½•åœ°æ–¹ğŸ˜"
        
        url_encoded_message=$(echo "$message" | python -c "import urllib.parse; print(urllib.parse.quote(input()))")
        wget -qO- "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TG_TESTPD_ID }}&text=$url_encoded_message"
