name: TGæŽ¨é€

on:
  push:
    branches:
      - main
    paths:
      - 'addressesapi.txt'
  workflow_dispatch:  # æ‰‹åŠ¨è§¦å‘

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: åŠ è½½å½“å‰çš„ GitHub åº“
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get Beijing Time
      id: time
      run: |
        TIME_ZONE="Asia/Shanghai"
        CURRENT_TIME=$(TZ=${TIME_ZONE} date +"%Y-%m-%d %H:%M:%S")
        echo "::set-output name=current_time::${CURRENT_TIME}"
      
    - name: æ‰§è¡ŒæŽ¨é€
      run: |
        head -n 6 addressesapi.txt > addressesapi_truncated.txt
        while IFS= read -r line; do
          ips+="$(echo "$line" | sed 's/#/, /g')"$'\n'
        done < addressesapi_truncated.txt
        message="ä»Šæ—¥ä¼˜é€‰ For: ${{ steps.time.outputs.current_time }}
        
        ${ips}......æ›´å¤šä¼˜é€‰IPå¯é€šè¿‡è‡ªå®šä¹‰è®¢é˜…æ–¹å¼èŽ·å–
        â€”â€”â€”â€”
        vlesså¿«é€Ÿä½“éªŒè®¢é˜…åœ°å€ï¼šhttps://sub.cmliucdn.tk/auto
        vlessè‡ªå®šä¹‰è®¢é˜…è¯¦ç»†ä½¿ç”¨æ–¹æ³•ï¼š
        https://sub.cmliucdn.tk/sub?host=[ä½ çš„VlessåŸŸå]%26uuid=[ä½ çš„UUID]%26path=[ä½ çš„wsè·¯å¾„]
        
        å¿«é€Ÿè®¢é˜…æ–¹å¼,å¦‚æžœä½ çš„vlessæ˜¯é€šè¿‡workeréƒ¨ç½²å¯å¡«å…¥ä»¥ä¸‹å‚æ•°åŽèŽ·å–èŠ‚ç‚¹è®¢é˜…ä¿¡æ¯
        https://sub.cmliucdn.tk/sub?host=[ä½ çš„WorkeråŸŸå]%26uuid=[ä½ çš„UUID]
        å®žé™…ä½¿ç”¨æ—¶è¯·åŽ»æŽ‰[ ]ç¬¦å·ï¼ŒWorkeréƒ¨ç½²ä¼˜å…ˆä½¿ç”¨è‡ªå®šä¹‰åŸŸï¼ï¼ï¼
        â€”â€”â€”â€”
        vmesså¿«é€Ÿä½“éªŒè®¢é˜…åœ°å€ï¼šhttps://vmess.cmliucdn.tk/auto
        vmessè‡ªå®šä¹‰è®¢é˜…è¯¦ç»†ä½¿ç”¨æ–¹æ³•ï¼š
        https://vmess.cmliucdn.tk/sub?cc=[VmessæœåŠ¡åå­—]%26host=[ä½ çš„VmessåŸŸå]%26uuid=[ä½ çš„UUID]%26path=[ä½ çš„wsè·¯å¾„]%26alterid=[é¢å¤–ID]%26security=[åŠ å¯†æ–¹å¼]
        
        *cc éžå¿…å¡«é¡¹ï¼Œå¯èƒ½ä¼šå½±å“ä½¿ç”¨åœ¨çº¿è®¢é˜…è½¬æ¢,æŽ¨èä½¿ç”¨åœ°åŒºä»£å·ï¼Œä¾‹å¦‚HKã€SGã€US
        *alterid éžå¿…å¡«é¡¹ï¼Œé»˜è®¤0
        *security éžå¿…å¡«é¡¹ï¼Œé»˜è®¤auto
        
        å¿«é€Ÿè®¢é˜…æ–¹å¼
        https://vmess.cmliucdn.tk/sub?host=[ä½ çš„VmessåŸŸå]%26uuid=[ä½ çš„UUID]%26path=[ä½ çš„wsè·¯å¾„]
        
        å®žé™…ä½¿ç”¨æ—¶è¯·åŽ»æŽ‰[ ]ç¬¦å·ï¼Œæ³¨æ„workerä¸æ”¯æŒvmessï¼workerä¸æ”¯æŒvmessï¼workerä¸æ”¯æŒvmessï¼ï¼ï¼
        â€”â€”â€”â€”
        æ³¨æ„ï¼šæ‚¨å¯ä»¥å°†æ­¤é“¾æŽ¥åˆ†äº«ä¼ æ’­åˆ°ä»»ä½•åœ°æ–¹ðŸ˜
        é¡ºä¾¿ç»™3Kmfi6HPå¤§ä½¬ã€ç™½å«–å“¥ã€Mingyuå¤§ä½¬æ•¬ä¸ªç¤¼"
        
        # wget -qO- "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TG_TESTPD_ID }}&text=$message"
        curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
        -d "chat_id=${{ secrets.TG_PD_ID }}" \
        -d "text=${message}" \
        "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage"
        
